version: '3'

services:
  gs_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.gs
    ports:
      - "5001:5000"

  pdftotext_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.pdftotext
    ports:
      - "5002:5000"

  log_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.log
    ports:
      - "5003:5000"
